### ISSUE TITLE
Ubuntu?

### ISSUE THREAD

**Issue by jmartinho** [bakercp/ofxPS3EyeGrabber#11]
Hello 

I am trying to use this addon form Christopher Baker (ofxPS3EyeGrabber) in Linux Ubuntu (14.04.2 LTS), but unfortunately with no success (it gives a lot of compile errors in codeblocks).

Does anyone have experience with this addon in Linux Ubuntu? And how to make it working?

I need this addon to control the autogain parameters in 2 connected ps3eye cameras. I can not control gain parameters with ofVideoGrabber.

Thanks,
jmm

**Comment by bakercp** [comment]
Typically this addon is not used on linux because (I believe) Gstreamer can give you access to those parameters via the kernel driver (which supports all of this stuff).  This code was actually copied from the linux PS3 Eye kernel driver.  That said, I haven't done this ... but it should be possible.  Keep me posted and I'll do my best to support it!

**Comment by bakercp** [comment]
The develop-linux branch now supports this.  See the README for more information about how to get it to work with existing drivers.
