### ISSUE TITLE
187fps in Linux

### ISSUE THREAD

**Issue by pvnkmrksk** [bakercp/ofxPS3EyeGrabber#13]
I have been googling since days. It says 187 fps everywhere, but I don't seem to be able to get it working in linux. I can only reach 125 fps. I couldn't find any forum post or a blog regarding that. It mentions here 187fps, am I missing something? If this is the wrong place to ask, can you redirect me to right place. Thanks.

**Comment by bakercp** [comment]
What version of openFrameworks, Linux, etc are you using?  I just tested it and at 320x240, I can get a solid 187 fps (and a somewhat corrupted 205) from one camera.

**Comment by pvnkmrksk** [comment]
I am not using openFrameworks exactly. I am trying to use it in ROS. I finally figured out that I should be using the newer linux kernels. So, I finally managed to get solid 187. (someone should have a blog post on how to get it running!)

I am running Ubuntu 14.04 with 4.2.0-38-generic kernel.
Am I missing anything to get 205 fps.

**Comment by bakercp** [comment]
This is an addon for openFrameworks that bypasses the normal linux driver to allow a little more fine tuning, efficiency and cross platform capabilities within the openFrameworks environment.  So, I'm not sure what to say about getting it working at higher speeds in ROS, sorry.  I'm assuming you'd have to set the camera clock registers to the appropriate scale values (e.g. https://github.com/bakercp/ofxPS3EyeGrabber/blob/master/libs/ps3eye/src/ps3eye.cpp#L1181-L1184)

It's probably worth it to see if your linux drivers make any mention of this or perhaps they just stick to the slower, more stable values.

I'll close this issue since it isn't directly related to this repository.  Good luck!
